name: Build and Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p build/DEBIAN build/usr/local/bin build/usr/share/doc/xiv

          cp dist/debian/DEBIAN/* build/DEBIAN/
          cp xiv.py build/usr/local/bin/xiv
          cp README.md build/usr/share/doc/xiv/
          cp dist/debian/usr/share/doc/xiv/copyright build/usr/share/doc/xiv/

          chmod +x build/DEBIAN/postinst build/usr/local/bin/xiv
          dpkg-deb --build build xiv_${VERSION}_all.deb
          ln -s xiv_${VERSION}_all.deb xiv.deb

          cp xiv.py xiv
          chmod +x xiv

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            xiv.deb
            xiv
          body: |
            **Debian/Ubuntu:**
            ```bash
            curl -fsSL https://github.com/james-akl/xiv/releases/latest/download/xiv.deb -o xiv.deb
            sudo dpkg -i xiv.deb
            ```
            Uninstall: `sudo dpkg -r xiv` or `sudo apt remove xiv`

            **Linux/macOS/WSL:**
            ```bash
            curl -fsSL https://github.com/james-akl/xiv/releases/latest/download/xiv -o xiv
            chmod +x xiv
            sudo mv xiv /usr/local/bin/
            ```
            Uninstall: `sudo rm /usr/local/bin/xiv`
