name: Build and Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build package
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mkdir -p build/DEBIAN build/usr/bin build/usr/share/doc/xiv

          cp dist/debian/DEBIAN/* build/DEBIAN/
          cp xiv.py build/usr/bin/xiv
          cp README.md build/usr/share/doc/xiv/
          cp dist/debian/usr/share/doc/xiv/copyright build/usr/share/doc/xiv/

          chmod +x build/DEBIAN/postinst build/usr/bin/xiv
          dpkg-deb --build build xiv_${VERSION}_all.deb
          cp xiv_${VERSION}_all.deb xiv.deb

          cp xiv.py xiv
          chmod +x xiv

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            xiv_*.deb
            xiv.deb
            xiv
          body: |
            **Debian/Ubuntu:**
            ```bash
            curl -fsSL https://github.com/james-akl/xiv/releases/download/${{ github.ref_name }}/xiv_${{ github.ref_name }}.deb -o xiv.deb
            sudo dpkg -i xiv.deb
            ```

            **Linux/macOS/WSL:**
            ```bash
            curl -fsSL https://github.com/james-akl/xiv/releases/download/${{ github.ref_name }}/xiv -o xiv
            chmod +x xiv
            sudo mv xiv /usr/local/bin/
            ```

            > Use `latest` instead of `${{ github.ref_name }}` in the URL to get the newest version.
